/*//PROGRAMA PARA CALCULAR EL PROMEDIO DE TRES NOTAS
 * This source file was generated by the Gradle 'init' task
 */
package com.example.recuperaciongene;

import java.util.Scanner;

public class App {
    
public static void main(String[] args) {
    //Librería Scanner
        Scanner sc = new Scanner(System.in);
        
    // Ingresar variables
        double nota1, nota2, nota3,suma, promedio;
        
    //Ingresando notas a calcular
        System.out.println("============================");
        System.out.println("SISTEMA PARA CALCULAR NOTAS");
        System.out.println("============================");
        
    //Nota primer parcial
        System.out.print("Ingrese la nota del primer parcial: ");
        nota1 = sc.nextDouble();
    //Nota segundo parcial
        System.out.print("Ingrese la nota del segundo parcial: ");
        nota2 = sc.nextDouble();
    //Nota tercer parcial
        System.out.print("Ingrese la nota del tercer parcial: ");
        nota3 = sc.nextDouble();

        suma = (nota1 + nota2 + nota3);
        promedio = suma/3;
     //Condicion if
        if( suma>=21 && suma <=30) {  
        System.out.println("El estudiante aprobo directo,su nota es: "+ promedio);
        } else if (suma < 21 && suma >= 15) { //caso contrario
        System.out.println(" El estudiante debe dar el examen supletorio");
        double examen = sc.nextDouble();
        double porcentaje_promedio = promedio*0.6;
        double porcentaje_examen =examen*0.4;
        double total_examen = porcentaje_promedio + porcentaje_examen;
        //condicion if
        if (total_examen >=7){
            System.out.println("El estudiante aprueba con el examen final,su promedio es: 7,00 ");
        } else {
            System.out.println("El estudiante reprobo con examen final, su promedio es: "+total_examen);
        }
        }
        else{ 
            System.out.println("El estudiante aprueba directo, el promedio es: "+promedio);
        
        }  
        
    //Fin del sistema
       
    }
}
