/*//PROGRAMA PARA CALCULAR EL PROMEDIO DE TRES NOTAS
 * This source file was generated by the Gradle 'init' task
 */
package com.example.recuperaciongene;

import java.util.Scanner;

public class App {
    
public static void main(String[] args) {
    //Librería Scanner
        Scanner sc = new Scanner(System.in);
        
    // Ingresar variables
        double nota1, nota2, nota3,suma, promedio;
        
    //Ingresando notas a calcular
        System.out.println("============================");
        System.out.println("SISTEMA PARA CALCULAR NOTAS");
        System.out.println("============================");
        
    //Nota primer parcial
        System.out.print("Ingrese la nota del primer parcial: ");
        nota1 = sc.nextDouble();
    //Nota segundo parcial
        System.out.print("Ingrese la nota del segundo parcial: ");
        nota2 = sc.nextDouble();
    //Nota tercer parcial
        System.out.print("Ingrese la nota del tercer parcial: ");
        nota3 = sc.nextDouble();

        suma = (nota1 + nota2 + nota3);
        promedio = suma/3;

        System.out.println("El promedio es: " + promedio);
        
    //Fin del sistema
       
    }
}
